import type { Metadata } from "next";
import "./globals.css";
import CustomLayout from "./CustomLayout";

export const metadata: Metadata = {
  title: "딸기 마켓",
  description: "Generated by Dexter Yoon",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CustomLayout>{children}</CustomLayout>
      </body>
    </html>
  );
}
