import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/contexts";
import Root_Layout from "./_Layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Root_Layout>{children}</Root_Layout>
        </AuthProvider>
      </body>
    </html>
  );
}
